# Generated by Django 4.1.1 on 2022-10-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighFives',
        ),
    ]
