# Generated by Django 4.1.1 on 2022-10-13 23:38

from django.db import migrations
from django.utils import timezone


class Migration(migrations.Migration):

    def populate_db(apps, schema_editor):

        Blog = apps.get_model('blog', 'Blog')
        Comments = apps.get_model('blog', 'Comments')

        #Blogs
        onions_blog = Blog(title_text="Onions: The Cure All", author="Shrek himself",
                           content="evfs sdgh sd dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwgh dsg sdhsdf gdsfh dgshgdf gdsb fsgbfgs bsdbgfg dbfgsb dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vd dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrs tgb dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrs tgbrwv rwgvertgv rtwrwv rwgvertgv rtwfs gsfbd fvbrstgbrwv rwgvertgv rtwvdfs gsfbd fvbrstgbrwv rwgvertgv rtwdfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwsvw rwv dsvr tgvs sdthdy hstrt ghsd fhsdfg rths dsgfd fgew gfd g dfsg df sg fds g fdsg ewr g er ger wfg erwgf wesdfg gdsfg",
                           posted=timezone.now())
        onions_blog.save()
        farq_blog = Blog(title_text="How I became boujee in 7 days", author="Lord Farquaad",
                           content="adfge dfagds fgdfsg dsfgdsf gdfg dsf gfdsg dsfgdfs gdfsg dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwdfsg dsfg fdg sdfgdsf gdfsg dsfg dfsgdf sgdf gdsf gsdfg dsfg fdsg dsfgdfs gdsf gdfsg dsg dfsg fdsgdsf gdfs dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwfvbrstgbrwv rwgvertgv rtwgdfs gfdsg fa dsgfsdgf ewevfsdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwsvw rwv dsvr tgvs sdthdy hstrt ghsd fhsdfg rths dsgfd fgew gfd g dfsg df sg fds g fdsg ewr g er ger wfg dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwerwgf dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwwesdfg gdsfg",
                           posted=timezone.now())
        farq_blog.save()
        earwax_blog = Blog(title_text="Earwax: 101 uses", author="Shrek himself",
                         content="dsf bg sdg dsfg dsfgdbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtw dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgb dfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtw dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfg db fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtw dfshdsgh dfshg sdhgds hf dsh dfsh dfsh dfshgdf shdfs hsd hfd shdfs ghfds hdsfgh dfshdf shdfs hfdsh dfgsh fdhs adfge dfagdsfgdfsg dsfgdsf gdfg dsf gfdsg dsfgdfs gdf sg dfsg dsfg fdg sdfgdsf gdfsg dsfg dfsgdf sgdf gdsf gsdfg dsfg fdsg dsfgdfs gdsf gdfsg dsg dfsg fdsgdsf gdfs gdfs gfdsg fa dsgfsdgf ewevfsdvwe wdvfs vdf vdf vdfs gsfbd fv brst dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwgbrwv rwgvertgv rtwsvw rwv dsvr tgvs sdthdy hstrt ghsd fhsdfg rths dsgfd fgew gfd g dfsg df sg fds g fdsg ewr g er ger wfg erwgf wesdfg gdsfg",
                         posted=timezone.now())
        earwax_blog.save()
        ginger_blog = Blog(title_text="Overcoming Past Trauma: A Healthy Outlook", author="Gingerbread Man",
                         content="md dfg daf dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtw dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtw dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtw dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtw gsafgd arfd asg ewr fgwet gsdfg dfsg dsf gfdg dsfg adfge dfagdsfgdfsg dsfgdsf gdfg dsf gfdsg dsfgdfs gdfsg dfsg dsfg fdg sdfgdsf gdfsg dsfg dfsgdf sgdf gdsf gsdfg dsfg fdsg dsfgdfs gdsf gdfsg dsg dfsg fdsgdsf gdfs gdfs gfdsg fa dsgfsdgf ewevfsdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwsvw rwv dsvr tgvs sdthdy hstrt ghsd fhsdfg rths dsgfd fgew gfd g dfsg df sg fds g fdsg ewr g er ger wfg erwgf wesdfg  dbfgsb dfgbfgb dfgbdfg bdfgb fgbfg bdfgb dfgb dfgbdfg bfgdb fgb fgdb gfbfgd bfg bdfgb fdgb fgb dfgbfg bdfg bdvwe wdvfs vdfvdf vdfs gsfbd fvbrstgbrwv rwgvertgv rtwgdsfg",
                         posted=timezone.now())
        ginger_blog.save()



        #onions_blog comments
        nic_comment = Comments(blog=onions_blog, commenter="Gerey G.", email="guyman@hotmail.com",
                               content="Incredible",
                               posted=timezone.now())
        nic_comment.save()
        ni_comment = Comments(blog=onions_blog, commenter="Ron Swanson", email="ronny@hotmail.com",
                              content="eh. just eh.",
                              posted=timezone.now())
        ni_comment.save()
        dk_comment = Comments(blog=onions_blog, commenter="Donkey Kong", email="rollingbarrels27@hotmail.com",
                              content="Super sick. Just honored to be the first comment on this post.",
                              posted=timezone.now())
        dk_comment.save()
        fiona_comment = Comments(blog=onions_blog, commenter="Fiona", email="greenonions@hotmail.com",
                              content="Wow. I learned so much.",
                              posted=timezone.now())
        fiona_comment.save()
        mario_comment = Comments(blog=onions_blog, commenter="Mario", email="plumbing801@hotmail.com",
                              content="Really some great life advice here.",
                              posted=timezone.now())
        mario_comment.save()
        nick_comment = Comments(blog=onions_blog, commenter="Nicolas Cage", email="thatmovieguy@hotmail.com",
                              content="Thanks Shrek. You've always been like a son to me!",
                              posted=timezone.now())
        nick_comment.save()


        #farq_blog comments
        e_comment = Comments(blog=farq_blog, commenter="Bruski", email="bru@till.com",
                             content="Radical",
                             posted=timezone.now())
        e_comment.save()
        m_comment = Comments(blog=farq_blog, commenter="Trish", email="hello@yelp.com",
                             content="Fascinating",
                             posted=timezone.now())
        m_comment.save()
        dt_comment = Comments(blog=farq_blog, commenter="Donald Trump", email="moneytings@hotmail.com",
                              content="This is Huge.",
                              posted=timezone.now())
        dt_comment.save()
        em_comment = Comments(blog=farq_blog, commenter="Elon Musk", email="marsordeath@nxztllzytiyr.com",
                                 content="This article is to the moon...nah wait to Mars.",
                                 posted=timezone.now())
        em_comment.save()


        #earwax_blog comments
        grinch_comment = Comments(blog=earwax_blog, commenter="The Grinch", email="bigChristmasGuy@hotmail.com",
                              content="Adding earwax extractor to my Christmas list rn.",
                              posted=timezone.now())
        grinch_comment.save()
        harambe_comment = Comments(blog=earwax_blog, commenter="Harambe", email="backlikeineverleft@nyzoo.com",
                              content="Wow, I could see how this could be quite helpful...",
                              posted=timezone.now())
        harambe_comment.save()
        na_comment = Comments(blog=earwax_blog, commenter="Josh Triscaldson", email="bigguy@gmail.com",
                               content="Please reach out to me. I have an enquiry.",
                               posted=timezone.now())
        na_comment.save()
        nap_comment = Comments(blog=earwax_blog, commenter="Napolean Dynamite", email="totsandstuff@gmail.com",
                                  content="lol.",
                                  posted=timezone.now())
        nap_comment.save()




        #ginger_blog comments
        don_comment = Comments(blog=ginger_blog, commenter="Jonny Appleseed", email="treesordie@gmail.com",
                                content="Trees and stuff.",
                                posted=timezone.now())
        don_comment.save()
        do_comment = Comments(blog=ginger_blog, commenter="Jimmy", email="yep@gmail.com",
                                content="This is insightful.",
                                posted=timezone.now())
        do_comment.save()
        jc_comment = Comments(blog=ginger_blog, commenter="John Cena", email="heythereitsme@hotmail.com",
                              content="Big time. Big time baby.",
                              posted=timezone.now())
        jc_comment.save()
        donk_comment = Comments(blog=ginger_blog, commenter="Donkey", email="growingfather@gmail.com",
                              content="Ya'll like reading this stuff? lol",
                              posted=timezone.now())
        donk_comment.save()


    dependencies = [
        ('blog', '0002_delete_highfives'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
