# Generated by Django 4.1.2 on 2022-10-12 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_highfivelog'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HighFives',
        ),
    ]
