# Generated by Django 3.1.5 on 2022-11-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0003_delete_highfives'),
    ]

    operations = [
        migrations.AlterField(
            model_name='highfivelog',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
