# Generated by Django 2.2.6 on 2020-02-04 18:09

from django.db import migrations
from django.utils import timezone


def populate_db(apps, schema_editor):

    # Nuke 
    Choice = apps.get_model('polls', 'Choice')
    Choice.objects.all().delete()

    Question = apps.get_model('polls', 'Question')
    Question.objects.all().delete()

    # Pizza questions
    pizza_q = Question(question_text="Best kind of pizza?", pub_date=timezone.now())
    pizza_q.save()

    pepperoni = Choice(question=pizza_q, choice_text="Carnivore", votes=27)
    pepperoni.save()

    hawaiian = Choice(question=pizza_q, choice_text="The Real Dill", votes=13)
    hawaiian.save()

    combination = Choice(question=pizza_q, choice_text="Marghie", votes=42)
    combination.save()

    meat_lovers = Choice(question=pizza_q, choice_text="Carmen", votes=78)
    meat_lovers.save()


    # James Bond questions
    jamesbond_q = Question(question_text="Best James Bond actor?", pub_date=timezone.now())
    jamesbond_q.save()

    sean = Choice(question=jamesbond_q, choice_text="Sean Connery", votes=92)
    sean.save()

    pierce = Choice(question=jamesbond_q, choice_text="Pierce Brosnan", votes=47)
    pierce.save()

    roger = Choice(question=jamesbond_q, choice_text="Roger Moore", votes=29)
    roger.save()

    daniel = Choice(question=jamesbond_q, choice_text="Daniel Craig", votes=44)
    daniel.save()


    # Day of the week
    day_q = Question(question_text="Best day of the week?", pub_date=timezone.now())
    day_q.save()

    friday = Choice(question=day_q, choice_text="Friday!", votes=100)
    friday.save()

    saturday = Choice(question=day_q, choice_text="Saturday", votes=20)
    saturday.save()

    monday = Choice(question=day_q, choice_text="Monday", votes=-20)
    monday.save()

class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(populate_db),
    ]
